### ISSUE TITLE
TODO: Add add-ons packages

### ISSUE THREAD

**Issue by alexa-v2** [TheHitMan7/BiTGApps-ARM64#3]
This issue is to track the progress of the requested add-on packages

My base suggestion is:
- Google app (velvet): used for Google Assistant, Google Feed, Google Now, etc
- Google Dialer (duh)

Maybe in addition, as like extra extra addon
- GCam
- Chrome
- Play Games
- Google TTS
etc, etc

What's popular so far:
- Dialer
- Digital Wellbeing

Any suggestions welcome!

**Comment by hirengarai** [comment]
Please consider adding Digital Wellbeing as the grayscale after a certain time was very much helpful.

**Comment by TheHitMan7** [comment]
> Please consider adding Digital Wellbeing as the grayscale after a certain time was very much helpful.

Sure.

**Comment by AlwyNjOshy** [comment]
We value you time adding chrome  play games are wortgles, it can downloaded from directly, but make something that can be done by you like current bitgapps, if you spend time for unnecessary things later you will get tired and bored and may leave voding behind

**Comment by alexa-v2** [comment]
@AlwyNjOshy there will never be any battery optimization exceptions included in the package
And please be aware you aren't the only one using this package. Not everyone will share your views on what should be included and you don't have to flash any add-on package

**Comment by GhostLeader37** [comment]
I think the add-on should like this
Google : Google,Maps,Play Games,Drive,Street View,Keep Note
Google Daily App : Google Message, Google Dialer,Google Photos,Google Calendar,Google Clock
System Google App : Markup,Wellbeing, Google Storage, Device Health Service,Google Webview
And it should come with configuration setting like sauron-useroption on Ainur Sauron

**Comment by alexa-v2** [comment]
@GhostLeader37 config file is in the works, but no ETA yet

I was thinking of a Plus package similiar to your "Google" pacakge

And dialer, messages, and carrier services as "Phone"

A couple other suggestions have been webview and wellbeing

**Comment by sickc** [comment]
Adding Android SetupWizard (com.google.android.setupwizard) would be fine for those who use online backups.

**Comment by TheHitMan7** [comment]
This going to be closed. Because i am providing only three Addon packages.

1. Google and Google Assistant
2. Wellbeing
3. Setupwizard

Thanks

**Comment by alexa-v2** [comment]
So you're going to completely ignore user feedback now @TheHitMan7?

**Comment by TheHitMan7** [comment]
> So you're going to completely ignore user feedback now @TheHitMan7?

Yes.
