### ISSUE TITLE
No restore from cloud functionality during setup

### ISSUE THREAD

**Issue by clienthax** [TheHitMan7/BiTGApps-ARM64#7]
Bitgapps Q Beta 5

After flashing rom+bitgapps from blank, during google account add, there is no option to restore backups from google, guessing this is due to a missing component somewhere?

**Comment by TheHitMan7** [comment]
> Bitgapps Q Beta 5
> 
> After flashing rom+bitgapps from blank, during google account add, there is no option to restore backups from google, guessing this is due to a missing component somewhere?

It is fixed in BETA 6, someone replied that google restore is fine with BETA 6.

**Comment by alexa-v2** [comment]
Parts of restore depend on setup wizard which isn't included in the base package
